// GETTING RECIPES
export const GET_RECIPES = "GET_RECIPES"
export const GET_RECIPES_SAGA = "GET_RECIPES_SAGA"

// USER LOGIN/LOGOUT
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"

// LOADING
export const LOADING = "LOADING"

// SEARCH
export const SEARCHING = "SEARCHING"

// MENU RECIPES
export const ADD_RECIPE = "ADD_RECIPE"
export const DELETE_RECIPE = "DELETE_RECIPE"